### PR TITLE
Fix the VM name lazy intialize

### LINKED ISSUE #56: bug: machines fails to reconcile due to wrong name
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
 failureMessage: expected VM name to match "capmox-e2e-p0jq9a-control-plane-b4t76"     but it was "capmox-e2e-buedhi-control-plane-cskrb"
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-proxmox version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Closes #56

### CODE REVIEW

File: internal/service/vmservice/find.go [hunk 1]
```diff
@@ -35,6 +35,9 @@ var (
 
 	// ErrVMNotFound VM is not Found in Proxmox.
 	ErrVMNotFound = errors.New("vm not found")
+
+	// ErrVMNotInitialized VM is not Initialized in Proxmox.
+	ErrVMNotInitialized = errors.New("vm not Initialized")
```
Comment (wikkyk) [inline internal/service/vmservice/find.go:40]: nitpick: no need for capital i here

File: internal/service/vmservice/find.go [hunk 2]
```diff
@@ -50,6 +53,10 @@ func FindVM(ctx context.Context, scope *scope.MachineScope) (*proxmox.VirtualMac
 			scope.Error(err, "unable to find vm")
 			return nil, ErrVMNotFound
 		}
+		if vm.Name != scope.ProxmoxMachine.GetName() {
+			scope.Error(err, "VM is not initialized yet")
```
Comment (wikkyk) [inline internal/service/vmservice/find.go:57]: nitpick: consistent capitalisation (`vm` vs `VM`)

**Review by wikkyk — DISMISSED** [review]
Just minor spelling nitpicks.
Please don't forget to squash before merging.

**Review by wikkyk — APPROVED** [review]
